import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/utils/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen p-0 m-0 flex flex-col items-center bg-white`}
      >
        <Providers>
          <div className="w-full h-full bg-neutral-200/50 dark:bg-neutral-950 text-neutral-900 dark:text-neutral-200">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
